USE Master
GO

IF EXISTS (SELECT * FROM sys.databases WHERE NAME = 'FilmReference')
	ALTER DATABASE FilmReference SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
	DROP DATABASE FilmReference
GO

CREATE DATABASE FilmReference
GO

USE FilmReference
GO

CREATE TABLE Person (
	PersonId INT NOT NULL IDENTITY (1, 1),
	FirstName NVARCHAR(50) NULL,
	LastName NVARCHAR(50) NULL,
	Description NVARCHAR(200) NOT NULL,
	IsActor BIT NOT NULL,
	IsDirector BIT NOT NULL,
	Picture VARBINARY(MAX) NULL,
	CONSTRAINT PK_Person PRIMARY KEY (PersonId)
)
GO

CREATE TABLE Genre (
	GenreId INT NOT NULL IDENTITY (1, 1),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(500) NULL,
	CONSTRAINT PK_Genre PRIMARY KEY (GenreId)
)
GO

CREATE TABLE Studio (
	StudioId INT NOT NULL IDENTITY (1, 1),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(500) NULL,
	Picture VARBINARY(MAX) NULL,
	CONSTRAINT PK_Studio PRIMARY KEY (StudioId)
)
GO

CREATE TABLE Film (
	FilmId INT NOT NULL IDENTITY (1, 1),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(500) NOT NULL,
	Picture VARBINARY(MAX) NULL,
	GenreId INT NOT NULL,
	DirectorId INT NOT NULL,
	StudioId INT NOT NULL,
	CONSTRAINT PK_Film PRIMARY KEY (FilmId),
	CONSTRAINT FK_Film_Genre FOREIGN KEY (GenreId)
		REFERENCES Genre (GenreId),
	CONSTRAINT FK_Film_Person FOREIGN KEY (DirectorId)
		REFERENCES Person (PersonId),
	CONSTRAINT FK_Film_Studio FOREIGN KEY (StudioId)
		REFERENCES Studio (StudioId)
)
GO

CREATE TABLE FilmPerson (
	FilmPersonId INT NOT NULL IDENTITY (1, 1),
	FilmId INT NOT NULL,
	PersonId INT NOT NULL,
	CONSTRAINT PK_FilmPerson PRIMARY KEY (FilmPersonId),
	CONSTRAINT FK_FilmPerson_Film FOREIGN KEY (FilmId)
		REFERENCES Film (FilmId),
	CONSTRAINT FK_FilmPerson_Person FOREIGN KEY (PersonId)
		REFERENCES Person (PersonId)
)
GO

ALTER TABLE Person ALTER COLUMN Description NVARCHAR(200) NULL
GO

USE FilmReference
ALTER TABLE Person ADD FullName AS
	CASE
		WHEN LastName IS NULL THEN FirstName
		WHEN FirstName IS NULL THEN LastName
		ELSE FirstName + ' ' + LastName
	END
GO